{
 "title": "Bitrise Dashboard",
 "description": "Build List, Build Time, Build Queue",
 "tags": [ "bitrise" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Running Builds",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "target": "running", "type": "table" }
   ]
  },
  {
   "title": "Build Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "builds", "type": "timeseries" }
   ]
  },
  {
   "title": "Build Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "queue", "type": "timeseries" }
   ]
  }
 ]
}